version: "3.9"

services:
  rust-cuda:
    build: .
    image: rust-cuda-image
    container_name: rust-cuda-container

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    tty: true
    stdin_open: true